language: node_js

# Node versions: https://node.green/

matrix:
  include:
    - name: "browsers linux"
      os: "linux"
      node_js: "11.5.0"
#    - name: "browsers osx"
#      os: "osx"
#      node_js: "11.5.0"
#    - name: "browsers windows"
#      os: "windows"
#      node_js: "11.5.0"
    - name: "node old"
      os: "osx"
      node_js: "6.4.0"
      env: NODE_ONLY=true

sudo: false
cache: npm

addons:
  chrome: stable
  firefox: latest
#  browserstack:
#    username: "nikolaymakhonin1"
#    access_key:
#      # You shoud generate this for each repositories.
#      # See: https://docs.travis-ci.com/user/encryption-keys
#      secure: "LM/WH57minqUR6KnUpN88sJlIY54Se1xPDzQ7yvsMz51H66ZgLDuauzGjxBnmWRtRGIyJ6YMSiGfTKz0ErSQlGZsEiX65+ML8jyX1YMatE68kWpan/QvtF7NGorOX7ybbd+o0Emks8D6CJ1OJSbmhe7ztCgCLWekrlNqjI3n0XCa/AhqQ13CvjvtIgUj7uBYVae8by5wWmYb7661xFWUWs9q5VuX5kqkNyAErM2W9V3WbJzC9y5COgRAipPmC7DSLz59yROUnliqIj16padfPQDSx/Yat87kgJekaseBEFenz8DZ7Fkm5d+T7w7+7SLSyzgL7L1LSgR6dY6Yp7CmMgw8RcXRdy9UJb89o0yCCrxQBsDH7N3fqRFgBPVNQJ8brEP5e0Q8XAM9rjGTDv9zUAeJPF7D4ISDxjKZLm8+D/S+Ri8rElYlGZ3O68k+L09N5kiLWRFyTGufJc0kD6zJ3K9dOz4ZxeTn2KdHfJ/IdhmaKhfh8526+g2564UHMUSDb8mDNtTSru5yQgXCuFCu0k8b3WknMWIFrDYEa7okDe/I8vCDworVlIG1VCr9JyYcA/xqHaZ/0nkuUMFowqlysDYn8OHUeNHmoLXUwYrdT46j/OKMGx975dRUt7r2fN1sM3SBoy4nr1MW6ulI+QPt5cBZPSr21stvYtNoxLKCVlA="

services:
  - xvfb

before_install:
  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"
  - "npm install coveralls"

  # Setup Node.js version-specific dependencies
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 4 || npm rm --save-dev $(grep -E '\"eslint\\S*\"' package.json | cut -d'\"' -f2)"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
  -
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - sleep 3 # give xvfb some time to start

script:
  - if [[ ${NODE_ONLY} == true ]]; then
      npm run test:mocha;
    else
      npm run ci;
    fi
