language: node_js

# Node versions: https://node.green/

matrix:
  include:
    - name: "browsers linux"
      os: "linux"
      node_js: "11.5.0"
#    - name: "browsers osx"
#      os: "osx"
#      node_js: "11.5.0"
#    - name: "browsers windows"
#      os: "windows"
#      node_js: "11.5.0"
    - name: "node old"
      os: "osx"
      node_js: "6.4.0"
      env: NODE_ONLY=true

sudo: false
cache: npm

addons:
  chrome: stable
  firefox: latest
  browserstack:
    username: "nikolaymakhonin1"
    access_key:
      # You shoud generate this for each repositories.
      # See: https://docs.travis-ci.com/user/encryption-keys
      secure: "T+/kuUZye5Ip4wdP7i3BQCosXygyg56gC7ltZqyfqfKL0VslUZ/L+CC1VuAQXW1u4zzNSqSzsktscPAcjnMJ2x8wPhS3VdwkZFAkoKtd9ghhwIZE/FA3uxFLfubQ7DuqqTbD21Mw3Rvj+zZICOC6ZXW1vGbhliv7WIndeIrpIdtA25IOWnbiqfxxKUFA7BmJUY34uh0V1Jp8uFrTqk2sx4yw7ZgTArHGgC9mVi3oUWvckY2yYyotJ4qwFVUGw6Tv9y6qibnZkuGUNph3rQtYanr3SmwG/SVslurL7kC8XQ8fPvkJq5Zcw4XGPYZOtFSWykY8OkEcFKlMQ+LH/FKFFHesx+kqH9J4ErJ8+y/Rz1ZlAFdO/klIkZBHt3u4chXa0PFMtAYjCIMipxr2IdG9UElGuG/iwf/kvxFjF5rQr3a4EufFmfYNq5lpt0biGr7MRVrdWw8TbtnYQ0Kpa7AjpvYjvapaMs4zj60FjRMBGfGbVwN0VlJ4xSRLAGXoCfO80Ois/IAnY9qkJa94e7Q6AcO7EAxsUHkAsxhsXHS7gcbkLWiAIpKPAf/ywUh4VZTYIdtJwc/HQBVNBPF10c04aE1W24xnlZfGYARAMM+/YVsjbkflVJ4Vs40EFjSvAjOW3vO0aNHr/QIxCVyLcoQRXnC8FInFA9v+ANc4B8ctfQM="

services:
  - xvfb

before_install:
  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"
  - "npm install coveralls"

  # Setup Node.js version-specific dependencies
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 4 || npm rm --save-dev $(grep -E '\"eslint\\S*\"' package.json | cut -d'\"' -f2)"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
  -
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - sleep 3 # give xvfb some time to start

script:
  - if [[ ${NODE_ONLY} == true ]]; then
      npm run test:mocha;
    else
      npm run ci;
    fi
