language: node_js

# Node versions: https://node.green/

os:
  - linux

node_js:
  - "11.5.0"
#  - "6.4.0"

sudo: false
cache:
  directories:
    - node_modules

addons:
  chrome: stable
  firefox: latest

services:
  - xvfb

before_install:
  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"
  - "npm install coveralls"

  # Setup Node.js version-specific dependencies
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 4 || npm rm --save-dev $(grep -E '\"eslint\\S*\"' package.json | cut -d'\"' -f2)"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
  -
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - sleep 3 # give xvfb some time to start

script:
  # Run test script, depending on istanbul install
  - "npm run coverage"
after_script:
  - "cat ./.nyc_output/node/lcov.info ./.nyc_output/browser/lcov.info | coveralls"
